sudo: false
install: pip install -U tox coveralls
language: python
script: travis_wait 30 tox --develop
services:
  - docker
before_deploy:
  - docker pull lokalise/lokalise-cli@sha256:2198814ebddfda56ee041a4b427521757dd57f75415ea9693696a64c550cef21
condition: $TOXENV = lint