# Dockerfile for development
# Based on the production Dockerfile, but with development additions.
# Keep this file as close as possible to the production Dockerfile, so the environments match.

FROM python:3.7
LABEL maintainer="Sergey Isachenko <vortexius@gmail.com>"
VOLUME /config

WORKDIR /usr/src/app

# Copy build scripts
COPY Docker/ Docker/
RUN Docker/setup_docker_prereqs

# Install hass component dependencies
COPY requirements_all.txt requirements_all.txt

# Uninstall enum34 because some dependencies install it but breaks Python 3.4+.
# See PR #8103 for more info.
RUN pip3 install --no-cache-dir -r requirements_all.txt && \
    pip3 install --no-cache-dir mysqlclient psycopg2 uvloop cchardet cython

# BEGIN: Development additions

# Install git
RUN apt-get update \
  && apt-get install -y --no-install-recommends git \
  && rm -rf /var/lib/apt/lists/*

# Install nodejs
RUN curl -sL https://deb.nodesource.com/setup_7.x | bash - && \
    apt-get install -y nodejs

# Install tox
RUN pip3 install --no-cache-dir tox

# Copy over everything required to run tox
COPY requirements_test_all.txt setup.cfg setup.py tox.ini ./
COPY pytest/const.py pytest/const.py

# Prefetch dependencies for tox
COPY pytest/package_constraints.txt pytest/package_constraints.txt
RUN tox -e py36 --notest

# END: Development additions

# Copy source
COPY . .

CMD [ "python", "-m", "pytest", "--config", "/config" ]